[project]
name = "semantah"
version = "0.1.0"
description = "Vault-Gewebe Toolkit (Indexing, Graph, Related)"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.0,<3.0",
    "numpy>=1.25,<2.0",
    "pyarrow>=14.0,<15.0",
    "pyyaml>=6.0,<7.0",
    "sentence-transformers>=2.2,<3.0",
    "scikit-learn>=1.3,<2.0",
    "networkx>=3.0,<4.0",
    "rich>=13.0,<14.0",
]
