name: contracts-validate
on: [push, pull_request]

# Restrict the default permissions of the GITHUB_TOKEN.
# Adjust scopes as necessary for the jobs in this workflow.
permissions:
  contents: read

jobs:
  # Validate the contracts using a reusable workflow
  validate:
    uses: heimgewebe/metarepo/.github/workflows/contracts-validate.yml@contracts-v1
