name: contracts
on: { pull_request: {}, push: { branches:[main] }, workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  json-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON schemas
        run: |
          npm i -g ajv-cli@5 ajv-formats
          ajv validate --extend=ajv-formats -s contracts/semantics/node.schema.json -d '{}' || true
          ajv validate --extend=ajv-formats -s contracts/semantics/edge.schema.json -d '{}' || true
          ajv validate --extend=ajv-formats -s contracts/semantics/report.schema.json -d '{}' || true
  docs-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Docs present"; test -d docs || mkdir -p docs
