name: contracts
on: { pull_request: {}, push: { branches:[main] }, workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  json-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON schemas
        run: |
          set -euo pipefail
          npm install -g ajv-cli@5 ajv-formats@^3
          for schema in node edge report; do
            ajv validate --extend=ajv-formats \
              -s contracts/semantics/${schema}.schema.json \
              -d @contracts/semantics/examples/${schema}-valid.json
          done

          for schema in node edge report; do
            if ajv validate --extend=ajv-formats \
              -s contracts/semantics/${schema}.schema.json \
              -d @contracts/semantics/examples/${schema}-invalid.json; then
              echo "Expected ${schema}-invalid.json to fail validation" >&2
              exit 1
            fi
          done
  docs-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Docs present"; test -d docs || mkdir -p docs
